git:
  requireCommits: false
  changelog: npx auto-changelog --stdout --commit-limit 0 --unreleased --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs
github:
  release: true
npm:
  publish: false
hooks:
  after:bump: npx auto-changelog --package --starting-date 2022-02-15 --commit-limit 0 --tag-pattern 'v\d+.*'
